export enum DrawAction {
  Lock = "lock",
  Divider = "divider",
  Move = "move",
  Select = "select",
  Text = "text",
  Rectangle = "rectangle",
  Diamond = "diamond",
  Circle = "circle",
  Scribble = "freedraw",
  Arrow = "arrow",
  Line = "line",
  Eraser = "eraser",
  Image = "Image",
}
